# Generated by Django 3.2.6 on 2021-09-23 12:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Enter a service title')),
                ('subtitle', models.CharField(max_length=300, verbose_name='Short Title')),
                ('short_desc', models.TextField(verbose_name='Short Description')),
                ('details', models.TextField(verbose_name='Enter a details of your service')),
                ('required_doc', models.TextField(verbose_name='Required Documents Information of this service')),
                ('packages', models.TextField(verbose_name='Service Packages')),
                ('image', models.FileField(help_text='Only PNG, JPG, JPEG format supported', upload_to='services_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='Service image')),
                ('home_shown', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=100, verbose_name='Is shown in home?')),
                ('service_sequence', models.IntegerField(unique=True, verbose_name='Services ordering integer')),
            ],
        ),
        migrations.CreateModel(
            name='GetService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=300, verbose_name='Enter Your name')),
                ('phone_no', models.CharField(max_length=300, verbose_name='Enter your phone number')),
                ('district', models.CharField(max_length=300, verbose_name='Enter your district')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Enter your message (if any)')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GetEasyApp.services', verbose_name='Select Service')),
            ],
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=300, verbose_name='Advertisement Title')),
                ('about', models.TextField(verbose_name='Site About')),
                ('terms', models.TextField(verbose_name='Enter terms and conditions')),
                ('policy', models.TextField(verbose_name='Enter policy')),
                ('last_author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
