# Generated by Django 3.2.6 on 2021-09-24 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetEasyApp', '0002_auto_20210924_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='image_field',
            field=models.FileField(default=1, help_text='Only PNG, JPG, JPEG format supported', upload_to='services_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='Home Background hero image'),
            preserve_default=False,
        ),
    ]
